### ISSUE TITLE
Repository permissions for Netlify

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2023#1]
Adding the repository to Netlify requires granting some permissions, described [here](https://docs.netlify.com/configure-builds/repo-permissions-linking/). My attempts failed likely due to insufficient permissions to this repository - I don't have access to settings. If somebody can grant permissions same as to the [BioC2022](https://github.com/Bioconductor/BioC2022), I'll continue trying.

**Comment by lshep** [comment]
permissions should be allowed now.  Please try again


Lori Shepherd - Kern

Bioconductor Core Team

Roswell Park Comprehensive Cancer Center

Department of Biostatistics & Bioinformatics

Elm & Carlton Streets

Buffalo, New York 14263

________________________________
From: Mikhail Dozmorov ***@***.***>
Sent: Thursday, December 8, 2022 9:15 PM
To: Bioconductor/BioC2023 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bioconductor/BioC2023] Repository permissions for Netlify (Issue #1)


Adding the repository to Netlify requires granting some permissions, described here<https://secure-web.cisco.com/1Wer2LKcDXMU-wWEpEV2c4kN5AuDPWelLyHiO30tLY2Na5b2aZbJG0ApsYQHUkJsgK2fi0_kVfm2TT9oXZaIGD9eF4oDmajpbGfqqYTApfH5p-hueR1pe6vEENR7l-VKacCDwcFhewoczaSrf5Lem4H_rmiVaeQpzgNRpq2wGn5KwKSyd1-C9WlLtmEGlRm4KNdSU9jaKmvIRqgiXJKT1T9AKNpqnbnRt3K583iHv-YZBRfXNSQ-iSn6-82LmSJQu-i2ekDEhwk1SypBGLwRo2meAdrV_TygSusgrhe4BbsSxuWbuzjwFTdUoVzDh5yV9/https%3A%2F%2Fdocs.netlify.com%2Fconfigure-builds%2Frepo-permissions-linking%2F>. My attempts failed likely due to insufficient permissions to this repository - I don't have access to settings. If somebody can grant permissions same as to the BioC2022<https://secure-web.cisco.com/1iLXsBNK5fsVEDOz_MB6yGJGsyqm1XVbn6j70XACsbcd_kz-PuyIRxTU3hlEpuiy0_weg8yKp-NPxIHk2Ox0rIqRfT2JYsKK2k8yCsxMoNGtPk9KPciOjcU2h36G3MrtLBrrJrc0pazltbEr7YFBsK5rknfVsBYKtXvYuQvZXALw7HCA1hTPBfBoXCQkafgUKiHp8ZbqGfiQDADo_9oF22ZOH8ChMhKS5OB2ck1mu-xdSAK_KHUIdl-ewu8uoWdR67oRGF9PbUd1-8kB5sdcXRCelXd0qjXvlxv0Vz1WedVwA1veDNcZxe3tmiH_SPLJA/https%3A%2F%2Fgithub.com%2FBioconductor%2FBioC2022>, I'll continue trying.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1ejD75GvWT3L-jQgszNDXINwZgUP2w6zurARbCop4P9JQ6ouf6Yeu2AbIOSWf0_xF7zwW8kU7glkn5sGeU8FLBkWMDihODjGMIHqvr6X7Uz3sjeJa_y1Fy5AOCJujhM-putHQK04VhjKwOxC4qa2mk9HwT3Vz4oKAIwnvl5aXmvrd_5JwGK5iUp33NAXwqxjGWzf5_jNEM-ybeg82EJS-JXAX1KN-NzoFkVyKMK8lGVS-TGW5ODhnafCoTjRI_hyNjjkeiB8LdBkecyXAJXjtlWVrmwNGRH1WjiwAKVWK2hkvs2g4imfJfswHzZgX3Xzm/https%3A%2F%2Fgithub.com%2FBioconductor%2FBioC2023%2Fissues%2F1>, or unsubscribe<https://secure-web.cisco.com/12y1eQgnQYWaVgCyXISU4CDhQvi-9V6TJiwoRSJJOAt1C3NnhwsdmvTWjxMo-9wP1gI0aEwqJJD9QKRzlOmCfsHHYFP-BKG5ySKJ_7vnJm12WPQ9egiInV-ntWYaNv6EMteuUWgsIgejHB4ETHmQjv_NRhwEwvwMo6ZCRGjXQ-3mztP4obBdedZNGNGHg0ogKwgnqAp__pf1d9Wh_a8blmXI4REFNaPkQX5jynHHszAtWIIBHYT36nwRVrBEYnH1Em881wGLZd-uIZVxI-7tZ7CxiGxElgpB3AgBIhZjtMQ3uash6nFXb0k4lpTqCBwMQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEO3MHD3HCAFTOJVXXRBCNDWMKI2LANCNFSM6AAAAAASY2BT6E>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


This email message may contain legally privileged and/or confidential information.  If you are not the intended recipient(s), or the employee or agent responsible for the delivery of this message to the intended recipient(s), you are hereby notified that any disclosure, copying, distribution, or use of this email message is prohibited.  If you have received this message in error, please notify the sender immediately by e-mail and delete this email message from your computer. Thank you.

**Comment by mdozmorov** [comment]
Thanks, Lori, it works, https://bioc2023-test.netlify.app/. Now, we need the official bioc2023.bioconductor.org, but that's a separate issue.
